export class ItemPurchaseValidation{
  public  TransactionId?:boolean
  public Reason?:boolean
  public TransactionType?:boolean
  public Quantity?:boolean
  public UnitCost?:boolean
  public UnitSale?:boolean
  public InStock?:boolean
  public DiscountAmount?:boolean
  public Vat?:boolean
  public Tax?:boolean
  public SerialNo?:boolean
  public TransactionDate?:boolean
  public Comments?:boolean
  public GrvNo?:boolean
  public InvoiceNo?:boolean
  public ChalanNo?:boolean
  public Item_Id?:boolean
  public Location_Id?:boolean
  public Supplier_Id?:boolean
  public Party_Id?:boolean
  public Customer_Id?:boolean
  public GrvDate?:boolean
  public Approver_Id?:boolean
  public Ledger_Id?:boolean
  public SubLedger_Id?:boolean
  public PaymentMode?:boolean
  public DiscountRateTransaction?:boolean
  public DiscountRateGroup?:boolean
  public TotalAmountTransaction?:boolean
  public TotalAmountGroup?:boolean
  public NetPayableAmount?:boolean
  public PaidAmount?:boolean
  public QuantityGroup?:boolean
  public LotNo?:boolean
  public DiscountAmountGroup?:boolean
}