using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
namespace ERP.DataService.Model.Model
{
    [Table("tblVoucher")]
    public class Voucher
    {
        [Key]
        [Column(TypeName = "VARCHAR")]
        [StringLength(100)]
        public string Id { set; get; }
         [StringLength(30)]
        public string Voucherno { get; set; }
        public DateTime? Voucherdate { get; set; }
        public string Vouchertype { get; set; }
        public bool? Voucherstatus { get; set; }
        public bool? PostingStatus { get; set; }
         [StringLength(1000)]
        public string Chequeno { get; set; }
        public string Chequedate { get; set; }
         [StringLength(200)]
        public string Bankname { get; set; }
         [StringLength(30)]
        public string BankAccountNo { get; set; }
         [StringLength(2000)]
        public string Particulars { get; set; }
         [Column(TypeName = "VARCHAR")]
         [StringLength(100)]
        public string PreparedBy { get; set; }
         [Column(TypeName = "VARCHAR")]
         [StringLength(100)]
        public string ApprovedBy { get; set; }
         [Column(TypeName = "VARCHAR")]
         [StringLength(100)]
        public string CheckedBy { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public string BranchID { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? EntryDate { get; set; }
        public DateTime? ModificationDate { get; set; }
        public DateTime? ApprovedTime { get; set; }
        public bool? IsVatTax { get; set; }
    }

}
