using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace ERPWebApiService.DataConnection
{
    public static class DatabaseCommand
    {
        public static int ExcuteNonQuery(string sql,Dictionary<String,string> paramlist,string commandType)
        {
            using (SqlConnection con = new SqlConnection(ConnectionString.getConnectionString()))
            {
                SqlCommand cmd = new SqlCommand(sql, con);
                if (paramlist != null)
                {
                    foreach (KeyValuePair<string,string> param in paramlist)
                    {
                        cmd.Parameters.AddWithValue(param.Key,param.Value);
                    }
                }
                if (commandType != null)
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                }
                con.Open();
               return cmd.ExecuteNonQuery();
            }
        }
        public static int ExcuteObjectNonQuery(string sql, Dictionary<String, Object> paramlist, string commandType)
        {
            using (SqlConnection con = new SqlConnection(ConnectionString.getConnectionString()))
            {
                SqlCommand cmd = new SqlCommand(sql, con);
                if (paramlist != null)
                {
                    foreach (KeyValuePair<string, object> param in paramlist)
                    {
                        cmd.Parameters.AddWithValue(param.Key, param.Value);
                    }
                }
                if (commandType != null)
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                }
                con.Open();
                return cmd.ExecuteNonQuery();
            }
        }
        public static string GetAutoGeneratedCode(string name,string itemName)
        {
            using (SqlConnection con = new SqlConnection(ConnectionString.getConnectionString()))
            {
                SqlCommand cmd = new SqlCommand("procGenerateAutoCode", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@name", name);
                cmd.Parameters.AddWithValue("@productName", itemName);
                con.Open();
                string result=cmd.ExecuteScalar().ToString();
                if (result != "0")
                {
                    return result;
                }
                else
                {
                    return null;
                }
            }
        }
    }
}