using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ViewModel.Model
{
    public class VoucherInfo
    {
        public Guid Id { get; set; }
        public string VoucherNo { get; set; }
        public DateTime? VoucherDate { get; set; }
        public string VoucherType { get; set; }
        public bool? VoucherStatus { get; set; }
        public bool? PostingStatus { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public string Bankname { get; set; }
        public string BankAccountNo { get; set; }
        public string Particulars { get; set; }
        public string PreparedBy { get; set; }
        public Guid? ApprovedBy { get; set; }
        public Guid? CheckedBy { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public Guid? BranchID { get; set; }
        public List<VoucherDetailInfo> VoucherDetailsList { get; set; }
        public double? Amount { get; set; }

    }

}
