// <auto-generated />
namespace ERP.DataService.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creatingdbanduserinfotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatingdbanduserinfotable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808291653552_creating db and userinfo table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
