// <auto-generated />
namespace ERP.DataService.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingbranchandconfigurationtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingbranchandconfigurationtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121510363_adding branch and configuration table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
