namespace ERP.DataService.Model.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addingvoucher : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.tblVoucherDetails",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        VoucherNo = c.String(maxLength: 30),
                        Lineno = c.Int(),
                        Amount = c.Double(),
                        GroupId = c.Int(),
                        LevelId = c.Int(),
                        AccId = c.Int(),
                        Branch_Id = c.Guid(),
                        Voucher_Id = c.Guid(),
                        Account_Id = c.Guid(),
                        Vat = c.Double(),
                        Tax = c.Double(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.tblVoucher",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Voucherno = c.String(maxLength: 30),
                        Voucherdate = c.DateTime(),
                        Vouchertype = c.String(),
                        Voucherstatus = c.Boolean(),
                        PostingStatus = c.Boolean(),
                        Chequeno = c.String(maxLength: 1000),
                        Chequedate = c.String(),
                        Bankname = c.String(maxLength: 200),
                        BankAccountNo = c.String(maxLength: 30),
                        Particulars = c.String(maxLength: 2000),
                        PreparedBy = c.Guid(),
                        ApprovedBy = c.Guid(),
                        CheckedBy = c.Guid(),
                        IsAutoGenerated = c.Boolean(),
                        BranchID = c.Guid(),
                        TotalAmount = c.Double(),
                        EntryDate = c.DateTime(),
                        ModificationDate = c.DateTime(),
                        ApprovedTime = c.DateTime(),
                        IsVatTax = c.Boolean(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.tblVoucher");
            DropTable("dbo.tblVoucherDetails");
        }
    }
}
