namespace ERP.DataService.Model.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangeGuidToString : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.tblAccountOpening");
            DropPrimaryKey("dbo.tblAccountParentChildRelation");
            DropPrimaryKey("dbo.tblAccount");
            DropPrimaryKey("dbo.ApplicatonAccessLogs");
            DropPrimaryKey("dbo.tblBranchConfiguration");
            DropPrimaryKey("dbo.tblCategory");
            DropPrimaryKey("dbo.tblCustomer");
            DropPrimaryKey("dbo.tblCustomerSupplierTransactionDetail");
            DropPrimaryKey("dbo.Designation");
            DropPrimaryKey("dbo.EmployeeGrade");
            DropPrimaryKey("dbo.EmployeeSubGrade");
            DropPrimaryKey("dbo.FormControlPermssions");
            DropPrimaryKey("dbo.GradeStepSalaryItem");
            DropPrimaryKey("dbo.tblGroupItem");
            DropPrimaryKey("dbo.tblInventoryItem");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.tblItemTransaction");
            DropPrimaryKey("dbo.tblItemLocation");
            DropPrimaryKey("dbo.Manufactures");
            DropPrimaryKey("dbo.Offer");
            DropPrimaryKey("dbo.tblOfferSetup");
            DropPrimaryKey("dbo.tblParty");
            DropPrimaryKey("dbo.tblPartyTransaction");
            DropPrimaryKey("dbo.PasswordChangeHistories");
            DropPrimaryKey("dbo.SalaryItem");
            DropPrimaryKey("dbo.SessionManagements");
            DropPrimaryKey("dbo.tblSettingSellPrice");
            DropPrimaryKey("dbo.tblSubCategory");
            DropPrimaryKey("dbo.tblSubledgerOpening");
            DropPrimaryKey("dbo.tblSubledger");
            DropPrimaryKey("dbo.tblSubledgerTransaction");
            DropPrimaryKey("dbo.tblSupplier");
            DropPrimaryKey("dbo.tblSupplierTransaction");
            DropPrimaryKey("dbo.tblUnit");
            DropPrimaryKey("dbo.tblUserInfo");
            DropPrimaryKey("dbo.tblVoucherDetails");
            DropPrimaryKey("dbo.tblVoucher");
            AlterColumn("dbo.tblAccountOpening", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblAccountOpening", "Branch_Id", c => c.String());
            AlterColumn("dbo.tblAccountOpening", "Account_Id", c => c.String());
            AlterColumn("dbo.tblAccountParentChildRelation", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblAccountParentChildRelation", "ParentAccount_Id", c => c.String());
            AlterColumn("dbo.tblAccountParentChildRelation", "ChildAccount_Id", c => c.String());
            AlterColumn("dbo.tblAccountParentChildRelation", "Branch_Id", c => c.String());
            AlterColumn("dbo.tblAccount", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblAccount", "BranchId", c => c.String());
            AlterColumn("dbo.tblAccount", "Corporate_Id", c => c.String());
            AlterColumn("dbo.tblAccount", "ControlLevel_Id", c => c.String());
            AlterColumn("dbo.ApplicatonAccessLogs", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.ApplicatonAccessLogs", "User_Id", c => c.String());
            AlterColumn("dbo.ApplicatonAccessLogs", "Session_Id", c => c.String());
            AlterColumn("dbo.tblBranchConfiguration", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblCategory", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblCustomer", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblCustomer", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblCustomer", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "Group_Id", c => c.String());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "CustomerTransaction_Id", c => c.String());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "SupplierTransaction_Id", c => c.String());
            AlterColumn("dbo.Designation", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.EmployeeGrade", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.EmployeeSubGrade", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.EmployeeSubGrade", "Grade_Id", c => c.String());
            AlterColumn("dbo.FormControlPermssions", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.GradeStepSalaryItem", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.GradeStepSalaryItem", "SalaryItem_Id", c => c.String());
            AlterColumn("dbo.GradeStepSalaryItem", "ComparatorItem_id", c => c.String());
            AlterColumn("dbo.GradeStepSalaryItem", "Grade_id", c => c.String());
            AlterColumn("dbo.GradeStepSalaryItem", "GradeStep_id", c => c.String());
            AlterColumn("dbo.GradeStepSalaryItem", "Salary_id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblGroupItem", "Group_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Supplier_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Party_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Customer_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Approver_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblGroupItem", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.tblInventoryItem", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblInventoryItem", "Category_Id", c => c.String());
            AlterColumn("dbo.tblInventoryItem", "SubCategory_Id", c => c.String());
            AlterColumn("dbo.tblInventoryItem", "UnitId", c => c.String());
            AlterColumn("dbo.tblInventoryItem", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblInventoryItem", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.Items", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Items", "SubMenu_Id", c => c.String());
            AlterColumn("dbo.tblItemTransaction", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblItemTransaction", "Group_Id", c => c.String());
            AlterColumn("dbo.tblItemTransaction", "Item_Id", c => c.String());
            AlterColumn("dbo.tblItemTransaction", "Location_Id", c => c.String());
            AlterColumn("dbo.tblItemLocation", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Manufactures", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Manufactures", "Country_Id", c => c.String());
            AlterColumn("dbo.Offer", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.Offer", "ValuableCustomerType_Id", c => c.String());
            AlterColumn("dbo.Offer", "OfferSetup_Id", c => c.String());
            AlterColumn("dbo.tblOfferSetup", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblOfferSetup", "Product_Id", c => c.String());
            AlterColumn("dbo.tblOfferSetup", "FreeProduct_Id", c => c.String());
            AlterColumn("dbo.tblParty", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblParty", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblParty", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.tblPartyTransaction", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblPartyTransaction", "Group_Id", c => c.String());
            AlterColumn("dbo.tblPartyTransaction", "Customer_Id", c => c.String());
            AlterColumn("dbo.tblPartyTransaction", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblPartyTransaction", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.PasswordChangeHistories", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.PasswordChangeHistories", "User_Id", c => c.String());
            AlterColumn("dbo.PasswordChangeHistories", "Branch_Id", c => c.String());
            AlterColumn("dbo.SalaryItem", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.SessionManagements", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SessionManagements", "User_Id", c => c.String());
            AlterColumn("dbo.SessionManagements", "Session_Id", c => c.String());
            AlterColumn("dbo.tblSettingSellPrice", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSettingSellPrice", "Item_Id", c => c.String());
            AlterColumn("dbo.tblSubCategory", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSubCategory", "Category_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerOpening", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSubledgerOpening", "Branch_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerOpening", "Account_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerOpening", "Subledger_Id", c => c.String());
            AlterColumn("dbo.tblSubledger", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSubledger", "Account_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerTransaction", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSubledgerTransaction", "Voucher_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerTransaction", "Voucher_Detail_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerTransaction", "Account_Id", c => c.String());
            AlterColumn("dbo.tblSubledgerTransaction", "Subledger_Id", c => c.String());
            AlterColumn("dbo.SubMenus", "Menu_Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSupplier", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSupplier", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblSupplier", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.tblSupplierTransaction", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblSupplierTransaction", "Group_Id", c => c.String());
            AlterColumn("dbo.tblSupplierTransaction", "Supplier_Id", c => c.String());
            AlterColumn("dbo.tblSupplierTransaction", "Ledger_Id", c => c.String());
            AlterColumn("dbo.tblSupplierTransaction", "SubLedger_Id", c => c.String());
            AlterColumn("dbo.tblUnit", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblUserInfo", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblUserInfo", "Employee_Id", c => c.String());
            AlterColumn("dbo.tblUserInfo", "Branch_Id", c => c.String());
            AlterColumn("dbo.tblUserInfo", "User_Level_Id", c => c.String());
            AlterColumn("dbo.tblVoucherDetails", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblVoucherDetails", "Branch_Id", c => c.String());
            AlterColumn("dbo.tblVoucherDetails", "Voucher_Id", c => c.String());
            AlterColumn("dbo.tblVoucherDetails", "Account_Id", c => c.String());
            AlterColumn("dbo.tblVoucher", "Id", c => c.String(nullable: false, maxLength: 100, unicode: false));
            AlterColumn("dbo.tblVoucher", "PreparedBy", c => c.String());
            AlterColumn("dbo.tblVoucher", "ApprovedBy", c => c.String());
            AlterColumn("dbo.tblVoucher", "CheckedBy", c => c.String());
            AlterColumn("dbo.tblVoucher", "BranchID", c => c.String());
            AddPrimaryKey("dbo.tblAccountOpening", "Id");
            AddPrimaryKey("dbo.tblAccountParentChildRelation", "Id");
            AddPrimaryKey("dbo.tblAccount", "Id");
            AddPrimaryKey("dbo.ApplicatonAccessLogs", "Id");
            AddPrimaryKey("dbo.tblBranchConfiguration", "Id");
            AddPrimaryKey("dbo.tblCategory", "Id");
            AddPrimaryKey("dbo.tblCustomer", "Id");
            AddPrimaryKey("dbo.tblCustomerSupplierTransactionDetail", "Id");
            AddPrimaryKey("dbo.Designation", "Id");
            AddPrimaryKey("dbo.EmployeeGrade", "Id");
            AddPrimaryKey("dbo.EmployeeSubGrade", "Id");
            AddPrimaryKey("dbo.FormControlPermssions", "Id");
            AddPrimaryKey("dbo.GradeStepSalaryItem", "Id");
            AddPrimaryKey("dbo.tblGroupItem", "Id");
            AddPrimaryKey("dbo.tblInventoryItem", "Id");
            AddPrimaryKey("dbo.Items", "Id");
            AddPrimaryKey("dbo.tblItemTransaction", "Id");
            AddPrimaryKey("dbo.tblItemLocation", "Id");
            AddPrimaryKey("dbo.Manufactures", "Id");
            AddPrimaryKey("dbo.Offer", "Id");
            AddPrimaryKey("dbo.tblOfferSetup", "Id");
            AddPrimaryKey("dbo.tblParty", "Id");
            AddPrimaryKey("dbo.tblPartyTransaction", "Id");
            AddPrimaryKey("dbo.PasswordChangeHistories", "Id");
            AddPrimaryKey("dbo.SalaryItem", "Id");
            AddPrimaryKey("dbo.SessionManagements", "Id");
            AddPrimaryKey("dbo.tblSettingSellPrice", "Id");
            AddPrimaryKey("dbo.tblSubCategory", "Id");
            AddPrimaryKey("dbo.tblSubledgerOpening", "Id");
            AddPrimaryKey("dbo.tblSubledger", "Id");
            AddPrimaryKey("dbo.tblSubledgerTransaction", "Id");
            AddPrimaryKey("dbo.tblSupplier", "Id");
            AddPrimaryKey("dbo.tblSupplierTransaction", "Id");
            AddPrimaryKey("dbo.tblUnit", "Id");
            AddPrimaryKey("dbo.tblUserInfo", "Id");
            AddPrimaryKey("dbo.tblVoucherDetails", "Id");
            AddPrimaryKey("dbo.tblVoucher", "Id");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.tblVoucher");
            DropPrimaryKey("dbo.tblVoucherDetails");
            DropPrimaryKey("dbo.tblUserInfo");
            DropPrimaryKey("dbo.tblUnit");
            DropPrimaryKey("dbo.tblSupplierTransaction");
            DropPrimaryKey("dbo.tblSupplier");
            DropPrimaryKey("dbo.tblSubledgerTransaction");
            DropPrimaryKey("dbo.tblSubledger");
            DropPrimaryKey("dbo.tblSubledgerOpening");
            DropPrimaryKey("dbo.tblSubCategory");
            DropPrimaryKey("dbo.tblSettingSellPrice");
            DropPrimaryKey("dbo.SessionManagements");
            DropPrimaryKey("dbo.SalaryItem");
            DropPrimaryKey("dbo.PasswordChangeHistories");
            DropPrimaryKey("dbo.tblPartyTransaction");
            DropPrimaryKey("dbo.tblParty");
            DropPrimaryKey("dbo.tblOfferSetup");
            DropPrimaryKey("dbo.Offer");
            DropPrimaryKey("dbo.Manufactures");
            DropPrimaryKey("dbo.tblItemLocation");
            DropPrimaryKey("dbo.tblItemTransaction");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.tblInventoryItem");
            DropPrimaryKey("dbo.tblGroupItem");
            DropPrimaryKey("dbo.GradeStepSalaryItem");
            DropPrimaryKey("dbo.FormControlPermssions");
            DropPrimaryKey("dbo.EmployeeSubGrade");
            DropPrimaryKey("dbo.EmployeeGrade");
            DropPrimaryKey("dbo.Designation");
            DropPrimaryKey("dbo.tblCustomerSupplierTransactionDetail");
            DropPrimaryKey("dbo.tblCustomer");
            DropPrimaryKey("dbo.tblCategory");
            DropPrimaryKey("dbo.tblBranchConfiguration");
            DropPrimaryKey("dbo.ApplicatonAccessLogs");
            DropPrimaryKey("dbo.tblAccount");
            DropPrimaryKey("dbo.tblAccountParentChildRelation");
            DropPrimaryKey("dbo.tblAccountOpening");
            AlterColumn("dbo.tblVoucher", "BranchID", c => c.Guid());
            AlterColumn("dbo.tblVoucher", "CheckedBy", c => c.Guid());
            AlterColumn("dbo.tblVoucher", "ApprovedBy", c => c.Guid());
            AlterColumn("dbo.tblVoucher", "PreparedBy", c => c.Guid());
            AlterColumn("dbo.tblVoucher", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblVoucherDetails", "Account_Id", c => c.Guid());
            AlterColumn("dbo.tblVoucherDetails", "Voucher_Id", c => c.Guid());
            AlterColumn("dbo.tblVoucherDetails", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.tblVoucherDetails", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblUserInfo", "User_Level_Id", c => c.Guid());
            AlterColumn("dbo.tblUserInfo", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.tblUserInfo", "Employee_Id", c => c.Guid());
            AlterColumn("dbo.tblUserInfo", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblUnit", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSupplierTransaction", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplierTransaction", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplierTransaction", "Supplier_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplierTransaction", "Group_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplierTransaction", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSupplier", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplier", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblSupplier", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SubMenus", "Menu_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerTransaction", "Subledger_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerTransaction", "Account_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerTransaction", "Voucher_Detail_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerTransaction", "Voucher_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerTransaction", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSubledger", "Account_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledger", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSubledgerOpening", "Subledger_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerOpening", "Account_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerOpening", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.tblSubledgerOpening", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSubCategory", "Category_Id", c => c.Guid());
            AlterColumn("dbo.tblSubCategory", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblSettingSellPrice", "Item_Id", c => c.Guid());
            AlterColumn("dbo.tblSettingSellPrice", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SessionManagements", "Session_Id", c => c.Guid());
            AlterColumn("dbo.SessionManagements", "User_Id", c => c.Guid());
            AlterColumn("dbo.SessionManagements", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SalaryItem", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.PasswordChangeHistories", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.PasswordChangeHistories", "User_Id", c => c.Guid());
            AlterColumn("dbo.PasswordChangeHistories", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblPartyTransaction", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblPartyTransaction", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblPartyTransaction", "Customer_Id", c => c.Guid());
            AlterColumn("dbo.tblPartyTransaction", "Group_Id", c => c.Guid());
            AlterColumn("dbo.tblPartyTransaction", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblParty", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblParty", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblParty", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblOfferSetup", "FreeProduct_Id", c => c.Guid());
            AlterColumn("dbo.tblOfferSetup", "Product_Id", c => c.Guid());
            AlterColumn("dbo.tblOfferSetup", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Offer", "OfferSetup_Id", c => c.Guid());
            AlterColumn("dbo.Offer", "ValuableCustomerType_Id", c => c.Guid());
            AlterColumn("dbo.Offer", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Manufactures", "Country_Id", c => c.Guid());
            AlterColumn("dbo.Manufactures", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblItemLocation", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblItemTransaction", "Location_Id", c => c.Guid());
            AlterColumn("dbo.tblItemTransaction", "Item_Id", c => c.Guid());
            AlterColumn("dbo.tblItemTransaction", "Group_Id", c => c.Guid());
            AlterColumn("dbo.tblItemTransaction", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Items", "SubMenu_Id", c => c.Guid());
            AlterColumn("dbo.Items", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblInventoryItem", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblInventoryItem", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblInventoryItem", "UnitId", c => c.Guid());
            AlterColumn("dbo.tblInventoryItem", "SubCategory_Id", c => c.Guid());
            AlterColumn("dbo.tblInventoryItem", "Category_Id", c => c.Guid());
            AlterColumn("dbo.tblInventoryItem", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblGroupItem", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Approver_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Customer_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Party_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Supplier_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Group_Id", c => c.Guid());
            AlterColumn("dbo.tblGroupItem", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.GradeStepSalaryItem", "Salary_id", c => c.Guid());
            AlterColumn("dbo.GradeStepSalaryItem", "GradeStep_id", c => c.Guid());
            AlterColumn("dbo.GradeStepSalaryItem", "Grade_id", c => c.Guid());
            AlterColumn("dbo.GradeStepSalaryItem", "ComparatorItem_id", c => c.Guid());
            AlterColumn("dbo.GradeStepSalaryItem", "SalaryItem_Id", c => c.Guid());
            AlterColumn("dbo.GradeStepSalaryItem", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.FormControlPermssions", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.EmployeeSubGrade", "Grade_Id", c => c.Guid());
            AlterColumn("dbo.EmployeeSubGrade", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.EmployeeGrade", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Designation", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "SupplierTransaction_Id", c => c.Guid());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "CustomerTransaction_Id", c => c.Guid());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "Group_Id", c => c.Guid());
            AlterColumn("dbo.tblCustomerSupplierTransactionDetail", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblCustomer", "SubLedger_Id", c => c.Guid());
            AlterColumn("dbo.tblCustomer", "Ledger_Id", c => c.Guid());
            AlterColumn("dbo.tblCustomer", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblCategory", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblBranchConfiguration", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ApplicatonAccessLogs", "Session_Id", c => c.Guid());
            AlterColumn("dbo.ApplicatonAccessLogs", "User_Id", c => c.Guid());
            AlterColumn("dbo.ApplicatonAccessLogs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblAccount", "ControlLevel_Id", c => c.Guid());
            AlterColumn("dbo.tblAccount", "Corporate_Id", c => c.Guid());
            AlterColumn("dbo.tblAccount", "BranchId", c => c.Guid());
            AlterColumn("dbo.tblAccount", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblAccountParentChildRelation", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.tblAccountParentChildRelation", "ChildAccount_Id", c => c.Guid());
            AlterColumn("dbo.tblAccountParentChildRelation", "ParentAccount_Id", c => c.Guid());
            AlterColumn("dbo.tblAccountParentChildRelation", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.tblAccountOpening", "Account_Id", c => c.Guid());
            AlterColumn("dbo.tblAccountOpening", "Branch_Id", c => c.Guid());
            AlterColumn("dbo.tblAccountOpening", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.tblVoucher", "Id");
            AddPrimaryKey("dbo.tblVoucherDetails", "Id");
            AddPrimaryKey("dbo.tblUserInfo", "Id");
            AddPrimaryKey("dbo.tblUnit", "Id");
            AddPrimaryKey("dbo.tblSupplierTransaction", "Id");
            AddPrimaryKey("dbo.tblSupplier", "Id");
            AddPrimaryKey("dbo.tblSubledgerTransaction", "Id");
            AddPrimaryKey("dbo.tblSubledger", "Id");
            AddPrimaryKey("dbo.tblSubledgerOpening", "Id");
            AddPrimaryKey("dbo.tblSubCategory", "Id");
            AddPrimaryKey("dbo.tblSettingSellPrice", "Id");
            AddPrimaryKey("dbo.SessionManagements", "Id");
            AddPrimaryKey("dbo.SalaryItem", "Id");
            AddPrimaryKey("dbo.PasswordChangeHistories", "Id");
            AddPrimaryKey("dbo.tblPartyTransaction", "Id");
            AddPrimaryKey("dbo.tblParty", "Id");
            AddPrimaryKey("dbo.tblOfferSetup", "Id");
            AddPrimaryKey("dbo.Offer", "Id");
            AddPrimaryKey("dbo.Manufactures", "Id");
            AddPrimaryKey("dbo.tblItemLocation", "Id");
            AddPrimaryKey("dbo.tblItemTransaction", "Id");
            AddPrimaryKey("dbo.Items", "Id");
            AddPrimaryKey("dbo.tblInventoryItem", "Id");
            AddPrimaryKey("dbo.tblGroupItem", "Id");
            AddPrimaryKey("dbo.GradeStepSalaryItem", "Id");
            AddPrimaryKey("dbo.FormControlPermssions", "Id");
            AddPrimaryKey("dbo.EmployeeSubGrade", "Id");
            AddPrimaryKey("dbo.EmployeeGrade", "Id");
            AddPrimaryKey("dbo.Designation", "Id");
            AddPrimaryKey("dbo.tblCustomerSupplierTransactionDetail", "Id");
            AddPrimaryKey("dbo.tblCustomer", "Id");
            AddPrimaryKey("dbo.tblCategory", "Id");
            AddPrimaryKey("dbo.tblBranchConfiguration", "Id");
            AddPrimaryKey("dbo.ApplicatonAccessLogs", "Id");
            AddPrimaryKey("dbo.tblAccount", "Id");
            AddPrimaryKey("dbo.tblAccountParentChildRelation", "Id");
            AddPrimaryKey("dbo.tblAccountOpening", "Id");
        }
    }
}
