// <auto-generated />
namespace ERP.DataService.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addinginventorysettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinginventorysettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201903080906188_adding inventory settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
