import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { AutoGeneratedAlertComponent } from './auto-generated-alert.component';

describe('AutoGeneratedAlertComponent', () => {
  let component: AutoGeneratedAlertComponent;
  let fixture: ComponentFixture<AutoGeneratedAlertComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ AutoGeneratedAlertComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(AutoGeneratedAlertComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
