import { Component, OnInit,Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';
import { DialogData } from '../../models/common/dialog-data.model';

@Component({
  selector: 'app-auto-generated-alert',
  templateUrl: './auto-generated-alert.component.html',
  styleUrls: ['./auto-generated-alert.component.css']
})
export class AutoGeneratedAlertComponent implements OnInit {

  constructor(
    public dialogRef: MatDialogRef<AutoGeneratedAlertComponent>,
    @Inject(MAT_DIALOG_DATA) public data: DialogData) {}

  onNoClick(): void {
    this.dialogRef.close(false);
  }
  ngOnInit(){
    debugger
  }
  createNew(){
    this.dialogRef.close(true);
  }
}
